const handleException = (inputArray, digit) => {};

module.exports = handleException;
